import AppKit
import Observation

struct ClipItem: Codable, Identifiable, Hashable {
    enum Kind: String, Codable { case text, link, image, files, color }

    var id = UUID()
    var kind: Kind
    var text: String?
    var longText = false
    var files: [String]?
    var width: Int?
    var height: Int?
    var rich: String?
    var appID: String?
    var appName: String?
    var date: Date
    var pinned = false
    var signature: String

    var title: String {
        switch kind {
        case .files:
            let names = (files ?? []).map { ($0 as NSString).lastPathComponent }
            return names.count > 1 ? "\(names[0]) +\(names.count - 1)" : names.first ?? ""
        case .image:
            return "\(width ?? 0) × \(height ?? 0)"
        default:
            return (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                .components(separatedBy: .newlines).first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) ?? ""
        }
    }
}

/// How a pasted string is filed: a bare URL, a colour, or plain text.
enum ClipClassify {
    static func kind(of trimmed: String) -> ClipItem.Kind {
        if !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme) {
            return .link
        }
        if trimmed.range(of: #"^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3}|[0-9a-fA-F]{8})$"#, options: .regularExpression) != nil
            || trimmed.range(of: #"^rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*(,\s*[\d.]+\s*)?\)$"#, options: .regularExpression) != nil {
            return .color
        }
        return .text
    }
}

/// Pinned clips stay. Everything else is kept up to `limit`, oldest first to go.
enum ClipHistoryRules {
    static func trimmed(_ items: [ClipItem], limit: Int) -> [ClipItem] {
        var unpinned = 0
        var keep: [ClipItem] = []
        for item in items {
            if item.pinned {
                keep.append(item)
            } else {
                unpinned += 1
                if unpinned <= limit { keep.append(item) }
            }
        }
        return keep
    }
}

/// Everything copied, up to the limit in settings, with password managers and concealed data left out.
@MainActor
@Observable
final class ClipboardHistory {
    private(set) var items: [ClipItem] = []

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount
    @ObservationIgnored private var saveWork: DispatchWorkItem?
    @ObservationIgnored private let images = NSCache<NSString, NSImage>()
    @ObservationIgnored private var loaded = false
    @ObservationIgnored var limit = 1000
    /// While SAVISUL borrows the clipboard to read a selection, its own copy isn't history.
    @ObservationIgnored var paused = false

    static let marker = NSPasteboard.PasteboardType("com.savisul.clipboard")
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", "net.antelle.keeweb", "com.bitwarden.desktop"
    ]
    private static let ignoredApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx", "com.bitwarden.desktop",
        "org.keepassxc.keepassxc", "com.apple.keychainaccess", "com.apple.Passwords", "com.lastpass.LastPass", "com.dashlane.dashlanephonefinal"
    ]

    nonisolated static var folder: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("SAVISUL/Clipboard", isDirectory: true)
    }

    private var indexURL: URL { Self.folder.appendingPathComponent("history.json") }
    nonisolated private static func file(_ id: UUID, _ ext: String) -> URL { folder.appendingPathComponent("\(id.uuidString).\(ext)") }

    func start() {
        load()
        guard timer == nil else { return }
        lastChange = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { _ in
            MainActor.assumeIsolated { Suite.shared.clipboard.history.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Panel renders (--dump-panels) show a sample history held in memory: nothing is read from or written to disk.
    func preview(_ sample: [ClipItem]) {
        loaded = true
        items = sample
    }

    private func load() {
        guard !loaded else { return }
        loaded = true
        try? FileManager.default.createDirectory(at: Self.folder, withIntermediateDirectories: true)
        guard let data = try? Data(contentsOf: indexURL) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        items = (try? decoder.decode([ClipItem].self, from: data)) ?? []
    }

    // MARK: Capture

    /// Skips whatever is on the clipboard now, after SAVISUL put the person's own contents back.
    func resync() {
        lastChange = NSPasteboard.general.changeCount
    }

    private func poll() {
        guard !paused else { return }
        let board = NSPasteboard.general
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount
        let types = Set((board.types ?? []).map(\.rawValue))
        guard !types.contains(Self.marker.rawValue), types.isDisjoint(with: Self.concealed) else { return }
        let front = NSWorkspace.shared.frontmostApplication
        if let id = front?.bundleIdentifier, Self.ignoredApps.contains(id) { return }
        guard var item = Self.read(board) else { return }
        item.appID = front?.bundleIdentifier
        item.appName = front?.localizedName
        insert(item, board: board)
    }

    private static func read(_ board: NSPasteboard) -> ClipItem? {
        let now = Date()
        if let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipItem(kind: .files, files: paths, date: now, signature: "f:" + paths.joined(separator: "|"))
        }
        let types = board.types ?? []
        let hasImage = types.contains(.png) || types.contains(.tiff)
        let string = board.string(forType: .string)
        if hasImage, string == nil || string?.isEmpty == true {
            guard let data = board.data(forType: .png) ?? board.data(forType: .tiff) else { return nil }
            return ClipItem(kind: .image, date: now, signature: "i:\(data.count):\(sample(data))")
        }
        guard let string, !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        let kind = ClipClassify.kind(of: trimmed)
        return ClipItem(kind: kind, text: string, date: now, signature: "t:\(string.count):\(sample(Data(string.utf8)))")
    }

    /// FNV-1a over up to 4096 evenly spaced bytes: stable across launches, unlike `hashValue`.
    private static func sample(_ data: Data) -> UInt64 {
        var hash: UInt64 = 0xcbf2_9ce4_8422_2325
        let step = max(data.count / 4096, 1)
        data.withUnsafeBytes { raw in
            guard let bytes = raw.bindMemory(to: UInt8.self).baseAddress else { return }
            var index = 0
            while index < data.count {
                hash = (hash ^ UInt64(bytes[index])) &* 0x100_0000_01b3
                index += step
            }
        }
        return hash
    }

    private func insert(_ fresh: ClipItem, board: NSPasteboard) {
        if let index = items.firstIndex(where: { $0.signature == fresh.signature }) {
            var existing = items.remove(at: index)
            existing.date = fresh.date
            existing.appID = fresh.appID ?? existing.appID
            existing.appName = fresh.appName ?? existing.appName
            items.insert(existing, at: 0)
            scheduleSave()
            return
        }
        var item = fresh
        switch item.kind {
        case .image:
            let png = board.data(forType: .png)
            guard let data = png ?? board.data(forType: .tiff), let image = NSImage(data: data),
                  let rep = image.representations.first else { return }
            item.width = rep.pixelsWide
            item.height = rep.pixelsHigh
            let id = item.id
            DispatchQueue.global(qos: .utility).async {
                let encoded = png ?? NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
                try? encoded?.write(to: Self.file(id, "png"), options: .atomic)
            }
            images.setObject(image, forKey: id.uuidString as NSString)
        case .text, .link, .color:
            if let text = item.text, text.count > 20_000 {
                let id = item.id
                let full = text
                DispatchQueue.global(qos: .utility).async { try? full.write(to: Self.file(id, "txt"), atomically: true, encoding: .utf8) }
                item.text = String(text.prefix(20_000))
                item.longText = true
            }
            if item.kind == .text {
                if let rtf = board.data(forType: .rtf) {
                    item.rich = "rtf"
                    let id = item.id
                    DispatchQueue.global(qos: .utility).async { try? rtf.write(to: Self.file(id, "rtf"), options: .atomic) }
                } else if let html = board.data(forType: .html) {
                    item.rich = "html"
                    let id = item.id
                    DispatchQueue.global(qos: .utility).async { try? html.write(to: Self.file(id, "html"), options: .atomic) }
                }
            }
        case .files:
            break
        }
        items.insert(item, at: 0)
        trim()
        scheduleSave()
    }

    private func trim() {
        let keep = ClipHistoryRules.trimmed(items, limit: limit)
        guard keep.count != items.count else { return }
        let kept = Set(keep.map(\.id))
        let drop = items.filter { !kept.contains($0.id) }
        items = keep
        drop.forEach(removeFiles)
    }

    private func removeFiles(_ item: ClipItem) {
        let id = item.id
        images.removeObject(forKey: id.uuidString as NSString)
        DispatchQueue.global(qos: .utility).async {
            for ext in ["png", "txt", "rtf", "html"] { try? FileManager.default.removeItem(at: Self.file(id, ext)) }
        }
    }

    private func scheduleSave() {
        saveWork?.cancel()
        let snapshot = items
        let url = indexURL
        let work = DispatchWorkItem {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .secondsSince1970
            if let data = try? encoder.encode(snapshot) { try? data.write(to: url, options: .atomic) }
        }
        saveWork = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.8, execute: work)
    }

    // MARK: Use

    func image(_ item: ClipItem) -> NSImage? {
        if let cached = images.object(forKey: item.id.uuidString as NSString) { return cached }
        guard let image = NSImage(contentsOf: Self.file(item.id, "png")) else { return nil }
        images.setObject(image, forKey: item.id.uuidString as NSString)
        return image
    }

    func fullText(_ item: ClipItem) -> String {
        if item.longText, let full = try? String(contentsOf: Self.file(item.id, "txt"), encoding: .utf8) { return full }
        return item.text ?? ""
    }

    /// Puts an item back on the clipboard, marked so the history does not record it twice.
    func write(_ item: ClipItem, plain: Bool) {
        let board = NSPasteboard.general
        board.clearContents()
        switch item.kind {
        case .files:
            let urls = (item.files ?? []).map { URL(fileURLWithPath: $0) as NSURL }
            board.writeObjects(urls)
        case .image:
            if let image = image(item) { board.writeObjects([image]) }
        case .text, .link, .color:
            let text = fullText(item)
            if !plain, let rich = item.rich, let data = try? Data(contentsOf: Self.file(item.id, rich)) {
                board.setData(data, forType: rich == "rtf" ? .rtf : .html)
            }
            board.setString(text, forType: .string)
        }
        board.setData(Data(), forType: Self.marker)
        lastChange = board.changeCount
        if let index = items.firstIndex(where: { $0.id == item.id }), index > 0 {
            var moved = items.remove(at: index)
            moved.date = Date()
            items.insert(moved, at: 0)
            scheduleSave()
        }
    }

    func paste(_ item: ClipItem, plain: Bool) {
        write(item, plain: plain)
        Keys.whenModifiersReleased { Keys.paste() }
    }

    /// Pastes what is on the clipboard now as plain text, then puts the original back.
    func pastePlain() {
        let board = NSPasteboard.general
        guard let text = board.string(forType: .string) else {
            Keys.whenModifiersReleased { Keys.paste() }
            return
        }
        let saved = (board.pasteboardItems ?? []).map { item -> [NSPasteboard.PasteboardType: Data] in
            var copy: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types { if let data = item.data(forType: type) { copy[type] = data } }
            return copy
        }
        board.clearContents()
        board.setString(text, forType: .string)
        board.setData(Data(), forType: Self.marker)
        lastChange = board.changeCount
        Keys.whenModifiersReleased {
            Keys.paste()
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.6) {
                MainActor.assumeIsolated {
                    let board = NSPasteboard.general
                    board.clearContents()
                    let restored = saved.map { types -> NSPasteboardItem in
                        let item = NSPasteboardItem()
                        for (type, data) in types { item.setData(data, forType: type) }
                        return item
                    }
                    board.writeObjects(restored)
                    Suite.shared.clipboard.history.lastChange = board.changeCount
                }
            }
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        scheduleSave()
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        removeFiles(item)
        scheduleSave()
    }

    func clear() {
        let dropped = items.filter { !$0.pinned }
        items.removeAll { !$0.pinned }
        dropped.forEach(removeFiles)
        scheduleSave()
    }
}
